### ISSUE TITLE
Add a average calculator

### ISSUE THREAD

**Issue by itz-shakil-92** [itz-shakil-92/project2#1]

**Comment by itz-shakil-92** [comment]
average calculator

**Comment by SeaBebop** [comment]
Can you assign this to me? Also do you mean a find the average calculator or a basic calculator instead of a scientific one?

**Comment by mustafaazad03** [comment]
Hey, Can I make contribution here now ?

**Comment by iamrahulmeena** [comment]
avg added
pls accept

**Comment by itz-shakil-92** [comment]
done

**Comment by itz-shakil-92** [comment]
@iamrahulmeena do it again and submit

**Comment by iamrahulmeena** [comment]
<!DOCTYPE html>
<html>
<head>
  <title>Average</title>
</head>
<body>
  <h1>Average of two no.</h1>

  <label for="num1">Number 1:</label>
  <input type="number" id="num1"><br>

  <label for="num2">Number 2:</label>
  <input type="number" id="num2"><br>

  <button onclick="calculateAverage()">Calculate</button>

  <div id="result"></div>

  <script>
    function calculateAverage() {
      var num1 = parseFloat(document.getElementById("num1").value);
      var num2 = parseFloat(document.getElementById("num2").value);

      var average = (num1 + num2) / 2;

      document.getElementById("result").innerHTML = "Average: " + average;
    }
  </script>
</body>
</html>

**Comment by iamrahulmeena** [comment]
done

**Comment by itz-shakil-92** [comment]
done
